### ISSUE TITLE
How do you use a cloud-hosted service with this connector?

### ISSUE THREAD

**Issue by jrutter** [appcelerator/appc.mongo#6]
How do you use a cloud-hosted service with this connector? Such as mongolab or compose.io?

**Comment by dawsontoth** [comment]
Check out the [example.config.js](https://github.com/appcelerator/appc.mongo/blob/master/conf/example.config.js) -- If you point the `url` in the config for this connector to the URL given to you by MongoLab or Compose.IO when you created your DB, it'll work!

Is there some particular issue you're having with doing this? I personally know that the connector works with both of those Mongo server providers, because I've used it with both of them.

**Comment by jrutter** [comment]
Ah - that's good news. I keep getting this error message:
```
INFO   | starting connector/appc.mongo@1.1.7
Uncaught Exception Error loading connector/appc.mongo. Authentication failed.
Error: Error loading connector/appc.mongo. Authentication failed.
```
I can't figure out where this error message is coming from.

**Comment by jrutter** [comment]
Nevermind - I think I got it. Thanks so much!

**Comment by dawsontoth** [comment]
My pleasure!
